### PR TITLE
Trey Thompson's Palindrome Solution

### PR DESCRIPTION
**Pull request by treythompson152**
This is my fix to the accidental merge from earlier. I also fixed some of the HTML files that had bad links.

### CODE REVIEW

**Review by coopersenior — APPROVED** [review]
+10
Ran test from branch. Worked correctly. 
Screenshot 2024-03-19 at 12 12 24 PM

**Review by cjoppa — APPROVED** [review]
+1
Both the solution and the tests look great! Good naming and clear testing

**Review by bennett-sampson — APPROVED** [review]
+1

**Comment by Allingsen** [comment]
+1
Everything looks good

**Review by ryangross1 — COMMENTED** [review]
Works nice! +10
Screenshot (271)

**Pull request merged**
