### PR TITLE
FizzBuzz Solution - Joppa

### PR DESCRIPTION
**Pull request by cjoppa**
Solution to FizzBuzz written in C# - take a look at the readme for info on running instructions

### CODE REVIEW

**Review by yabetsebren — COMMENTED** [review]
+1

the README file has a clear instruction. Code looks good.

**Review by gaparker716 — COMMENTED** [review]
I couldn't get it to run on my computer. Do I need to download dotnet or something?
joppa_notwork

**Comment by cjoppa** [comment]
> I couldn't get it to run on my computer. Do I need to download dotnet or something? joppa_notwork



Oops yes! My solution is in C#, so I believe you will need to download dotnet. Hopefully that will allow you to run it!

**Review by coopersenior — APPROVED** [review]
+10
Screenshot 2024-03-21 at 2 49 11 PM

**Pull request merged**
