### PR TITLE
Connor Carlson Palindrome Solution

### PR DESCRIPTION
**Pull request by Waterboy1887**

### CODE REVIEW

**Comment by doddsip** [comment]
+1 README.md file is readable, and all the instructions work. Code looks good!

**Comment by doddsip** [comment]
+10

The program works on my computer, and the tests work.

Capture

**Review by doddsip — APPROVED** [review]
Everything looks good.

**Comment by Waterboy1887** [comment]
matthew-parker-test
+10 review as well

**Pull request merged**
