### PR TITLE
submitting palindrome problem

### PR DESCRIPTION
**Pull request by doddsip**
for assignment 3. make sure to read the README.md file

### CODE REVIEW

**Review by mrolls13 — DISMISSED** [review]

**Comment by doddsip** [comment]
added test files!

**Comment by gaparker716** [comment]
+10 got the unit tests working
matthew_plus10

**Review by Waterboy1887 — APPROVED** [review]
Code and everything looks good to me. Looks like you just have a conflict to resolve in palindrome/index.html.

**Comment by Waterboy1887** [comment]
matthew-parker-test
+10 review as well

**Comment by mrolls13** [comment]
> added test files!

+1 for the added tests and +10 for working code as shown below:
Screenshot (947)

On a side note, at least for me I have to run run.sh before test.sh works. Probably has something to do with compiling, but the error message I got wasn't super helpful.

**Comment by sleddog** [comment]
@doddsip can you review this PR and merge/close it?

**Pull request merged**
