### PR TITLE
William Cade Sum of Primes Solution

### PR DESCRIPTION
**Pull request by MrGrapes2112**
Added my sum of primes problem solution w/ readme and bash shell

### CODE REVIEW

**Comment by yabetsebren** [comment]
- Doesn't echo result for ./runSum.sh
- Not sure if it takes any number from user or only works for default 17
- the unit test passes

Screenshot 2024-03-19 at 6 40 17 PM

**Comment by 20njohnson** [comment]
Screenshot 2024-03-21 at 4 52 30 PM
+10 - Everything worked great. Still waiting on a +1

**Review by 20njohnson — APPROVED** [review]

**Comment by 20njohnson** [comment]
Ah forgot: May need to change to allow for user input.

**Review by Jake-Ripley — APPROVED** [review]
+1 looks good

**Pull request merged**
